# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Next.js Static Site to GitHub Pages 

on:
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
    
#       - name: 📝 Load Environment Variables     
#         uses: c-py/action-dotenv-to-setenv@v2
#         with:
#           env-file: .env        
     
      - name: 🚗 Install Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: 📦 Get NPM Cache
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
          
      - name: 📦 Restore NPM Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 📦 Install NPM Dependencies
        run: npm ci --prefer-offline --no-audit
      
      - name: 💾 Restore Next.js Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - name: 🔥 Build Next.js Static Site  
        run: npm run export
        env:
          UNSPLASH_CLIENT_ID: ${{ secrets.UNSPLASH_CLIENT_ID }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
